//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fields {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fields.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;BaseTypes&quot;
        ///    targetNamespace=&quot;http://tempuri.org/BaseTypes.xsd&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns=&quot;http://tempuri.org/BaseTypes.xsd&quot;
        ///    xmlns:mstns=&quot;http://tempuri.org/BaseTypes.xsd&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///  &lt;xs:complexType name=&quot;IntBox&quot;/&gt;
        ///  &lt;xs:complexType name=&quot;StringBox&quot;/&gt;
        ///  &lt;xs:complexType name=&quot;CheckBoxField&quot; /&gt;
        ///  &lt;xs:complexType name=&quot;Calendar&quot; /&gt;
        ///&lt;/xs:schema&gt;.
        /// </summary>
        public static string baseType {
            get {
                return ResourceManager.GetString("baseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xs:schema id=&quot;XMLSchema1&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///  &lt;xs:complexType name=&quot;IntBox&quot;/&gt;
        ///  &lt;xs:complexType name=&quot;StringBox&quot;/&gt;
        ///  &lt;xs:complexType name=&quot;Group&quot; /&gt;
        ///&lt;/xs:schema&gt;.
        /// </summary>
        public static string BaseTypes {
            get {
                return ResourceManager.GetString("BaseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;XMLSchema1&quot;    
        ///    elementFormDefault=&quot;qualified&quot;   
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///&lt;xs:complexType name=&quot;Node1&quot;&gt;
        ///    &lt;xs:sequence&gt;
        ///
        ///      &lt;xs:element name=&quot;Name&quot; type=&quot;type1&quot;/&gt;
        ///      &lt;xs:element name=&quot;Age&quot; type=&quot;type0&quot;/&gt;
        ///
        ///    &lt;/xs:sequence&gt;
        ///  &lt;/xs:complexType&gt;
        ///&lt;/xs:schema&gt;.
        /// </summary>
        public static string Elem1 {
            get {
                return ResourceManager.GetString("Elem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:complexType name=&quot;type1&quot;&gt;
        ///    &lt;xs:complexContent mixed=&quot;false&quot;&gt;
        ///      &lt;xs:extension base=&quot;StringBox&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///          &lt;xs:element name=&quot;Value&quot;&gt;
        ///            &lt;xs:simpleType&gt;
        ///              &lt;xs:restriction base=&quot;xs:string&quot;&gt;
        ///                &lt;xs:minLength value=&quot;2&quot; /&gt;
        ///                &lt;xs:maxLength value=&quot;10&quot; /&gt;
        ///              &lt;/xs:restriction&gt;
        ///            &lt;/xs:simpleType&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Field1 {
            get {
                return ResourceManager.GetString("Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:complexType name=&quot;type0&quot;&gt;
        ///    &lt;xs:complexContent mixed=&quot;false&quot;&gt;
        ///      &lt;xs:extension base=&quot;IntBox&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///          &lt;xs:element name=&quot;Value&quot;&gt;
        ///            &lt;xs:simpleType&gt;
        ///              &lt;xs:restriction base=&quot;xs:integer&quot;&gt;
        ///                &lt;xs:minInclusive value=&quot;1&quot; /&gt;
        ///              &lt;/xs:restriction&gt;
        ///            &lt;/xs:simpleType&gt;
        ///          &lt;/xs:element&gt;
        ///        &lt;/xs:sequence&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Field2 {
            get {
                return ResourceManager.GetString("Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:complexType name=&quot;StringBox1&quot;&gt;
        ///    &lt;xs:complexContent mixed=&quot;false&quot;&gt;
        ///      &lt;xs:extension base=&quot;StringBox&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///          &lt;xs:element name=&quot;Value&quot; type=&quot;xs:string&quot;&gt;
        ///          &lt;/xs:element&gt;
        ///        &lt;/xs:sequence&gt;
        ///      &lt;/xs:extension&gt;
        ///    &lt;/xs:complexContent&gt;
        ///  &lt;/xs:complexType&gt;
        ///&lt;/xs:schema&gt;.
        /// </summary>
        public static string sb1 {
            get {
                return ResourceManager.GetString("sb1", resourceCulture);
            }
        }
    }
}
