//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xs:schema id=&quot;XMLSchema1&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///  &lt;xs:complexType name=&quot;IntBox&quot;/&gt;
        ///  &lt;xs:complexType name=&quot;StringBox&quot;/&gt;
        ///
        ///&lt;/xs:schema&gt;.
        /// </summary>
        public static string BaseTypes {
            get {
                return ResourceManager.GetString("BaseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;WORKFLOW name=&quot;workflow_1&quot;&gt;
        ///  
        ///  &lt;EDGES&gt;
        ///    &lt;EDGE from=&quot;workflow_1_node_2&quot; to=&quot;workflow_1_node_3&quot;&gt;
        ///      &lt;PRECONDITIONS/&gt;
        ///    &lt;/EDGE&gt;
        ///  
        ///    &lt;EDGE to=&quot;workflow_1_node_2&quot;/&gt;
        ///    
        ///    &lt;EDGE from=&quot;workflow_1_node_3&quot;/&gt;
        ///  
        ///  &lt;/EDGES&gt;
        ///  
        ///  &lt;NODES&gt;
        ///    &lt;workflow_1_node_1&gt;
        ///      &lt;SCHEMA&gt;
        ///        &lt;EXTENDEDTYPES/&gt;
        ///  
        ///        &lt;NODETYPE&gt;
        ///          &lt;xs:complexType name=&quot;workflow_1_node_1&quot;&gt;
        ///            &lt;xs:sequence/&gt;
        ///          &lt;/xs:complexType&gt;
        ///        &lt;/NODE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrowserTestState {
            get {
                return ResourceManager.GetString("BrowserTestState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PRECONDITIONS&gt;
        ///      &lt;AND&gt;
        ///
        ///        &lt;Greater&gt;
        ///          &lt;P0 type=&quot;operation&quot;&gt;
        ///            &lt;Sum&gt;
        ///              &lt;P0 type=&quot;operation&quot;&gt;
        ///                &lt;Length&gt;
        ///                  &lt;P0 type=&quot;path&quot; fieldType=&quot;StringBox&quot;&gt;
        ///                    //Node1/Name
        ///                  &lt;/P0&gt;
        ///                &lt;/Length&gt;
        ///              &lt;/P0&gt;
        ///              &lt;P1 type=&quot;operation&quot;&gt;
        ///                &lt;Length&gt;
        ///                  &lt;P0 type=&quot;path&quot;  fieldType=&quot;StringBox&quot;&gt;
        ///                    //Node1/Surname
        ///                  &lt;/P0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EdgePreconditions {
            get {
                return ResourceManager.GetString("EdgePreconditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PRECONDITIONS&gt;
        ///      &lt;AND&gt;
        ///
        ///        &lt;Greater&gt;
        ///          &lt;P0 type=&quot;operation&quot;&gt;
        ///
        ///              &lt;P0 type=&quot;operation&quot;&gt;
        ///                &lt;Length&gt;
        ///                  &lt;P0 type=&quot;path&quot;&gt;
        ///                    //Node1/Surname
        ///                  &lt;/P0&gt;
        ///                &lt;/Length&gt;
        ///              &lt;/P0&gt;
        ///
        ///          &lt;/P0&gt;
        ///          &lt;P1 type=&quot;value&quot;&gt;
        ///            &lt;IntBox&gt;
        ///              &lt;Value&gt;7&lt;/Value&gt;
        ///            &lt;/IntBox&gt;
        ///          &lt;/P1&gt;
        ///        &lt;/Greater&gt;
        ///
        ///      &lt;/AND&gt;
        ///    &lt;/PRECONDITIONS&gt;.
        /// </summary>
        public static string EdgePreconditions1 {
            get {
                return ResourceManager.GetString("EdgePreconditions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PRECONDITIONS&gt;
        ///      &lt;AND&gt;
        ///
        ///        &lt;Greater&gt;
        ///              &lt;P0 type=&quot;operation&quot;&gt;
        ///                &lt;Length&gt;
        ///                  &lt;P0 type=&quot;path&quot;&gt;
        ///                    //Node1/Name
        ///                  &lt;/P0&gt;
        ///                &lt;/Length&gt;
        ///              &lt;/P0&gt;
        ///          &lt;P1 type=&quot;value&quot;&gt;
        ///            &lt;IntBox&gt;
        ///              &lt;Value&gt;9&lt;/Value&gt;
        ///            &lt;/IntBox&gt;
        ///          &lt;/P1&gt;
        ///        &lt;/Greater&gt;
        ///
        ///      &lt;/AND&gt;
        ///    &lt;/PRECONDITIONS&gt;.
        /// </summary>
        public static string EdgePreconditions2 {
            get {
                return ResourceManager.GetString("EdgePreconditions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PRECONDITIONS&gt;
        ///          &lt;/PRECONDITIONS&gt;.
        /// </summary>
        public static string EdgePreconditions3 {
            get {
                return ResourceManager.GetString("EdgePreconditions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PRECONDITIONS&gt;
        ///          &lt;/PRECONDITIONS&gt;.
        /// </summary>
        public static string EdgePreconditions4 {
            get {
                return ResourceManager.GetString("EdgePreconditions4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PRECONDITIONS&gt;
        ///      &lt;AND&gt;
        ///
        ///        &lt;Greater&gt;
        ///          &lt;P0 type=&quot;operation&quot;&gt;
        ///            &lt;Substraction&gt;
        ///              &lt;P0 type=&quot;operation&quot;&gt;
        ///                &lt;Length&gt;
        ///                  &lt;P0 type=&quot;path&quot;&gt;
        ///                    //Node6/NomeFiglio2
        ///                  &lt;/P0&gt;
        ///                &lt;/Length&gt;
        ///              &lt;/P0&gt;
        ///              &lt;P1 type=&quot;operation&quot;&gt;
        ///                &lt;Length&gt;
        ///                  &lt;P0 type=&quot;path&quot;&gt;
        ///                    //Node6/NomeFiglio1
        ///                  &lt;/P0&gt;
        ///                &lt;/Leng [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EdgePreconditions5 {
            get {
                return ResourceManager.GetString("EdgePreconditions5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PRECONDITIONS&gt;
        ///          &lt;/PRECONDITIONS&gt;.
        /// </summary>
        public static string EdgePreconditions6 {
            get {
                return ResourceManager.GetString("EdgePreconditions6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PRECONDITIONS&gt;
        ///      &lt;AND&gt;
        ///
        ///        &lt;Greater&gt;
        ///          &lt;P0 type=&quot;operation&quot;&gt;
        ///            &lt;Substraction&gt;
        ///              &lt;P0 type=&quot;operation&quot;&gt;
        ///                &lt;Length&gt;
        ///                  &lt;P0 type=&quot;path&quot;&gt;
        ///                    //Node6/NomeFiglio1
        ///                  &lt;/P0&gt;
        ///                &lt;/Length&gt;
        ///              &lt;/P0&gt;
        ///              &lt;P1 type=&quot;operation&quot;&gt;
        ///                &lt;Length&gt;
        ///                  &lt;P0 type=&quot;path&quot;&gt;
        ///                    //Node6/NomeFiglio2
        ///                  &lt;/P0&gt;
        ///                &lt;/Leng [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EdgePreconditions7 {
            get {
                return ResourceManager.GetString("EdgePreconditions7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PRECONDITIONS&gt;
        ///      &lt;AND&gt;
        ///
        ///        &lt;Greater&gt;
        ///          &lt;P0 type=&quot;operation&quot;&gt;
        ///
        ///              &lt;P0 type=&quot;operation&quot;&gt;
        ///                &lt;Length&gt;
        ///                  &lt;P0 type=&quot;path&quot;&gt;
        ///                    //Node5/NomePadre
        ///                  &lt;/P0&gt;
        ///                &lt;/Length&gt;
        ///              &lt;/P0&gt;
        ///
        ///          &lt;/P0&gt;
        ///          &lt;P1 type=&quot;value&quot;&gt;
        ///            &lt;IntBox&gt;
        ///              &lt;Value&gt;10&lt;/Value&gt;
        ///            &lt;/IntBox&gt;
        ///          &lt;/P1&gt;
        ///        &lt;/Greater&gt;
        ///
        ///      &lt;/AND&gt;
        ///    &lt;/PRECONDITIONS&gt;.
        /// </summary>
        public static string EdgePreconditions8 {
            get {
                return ResourceManager.GetString("EdgePreconditions8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PRECONDITIONS&gt;
        ///      &lt;AND&gt;
        ///
        ///        &lt;Greater&gt;
        ///          &lt;P0 type=&quot;operation&quot;&gt;
        ///
        ///              &lt;P0 type=&quot;operation&quot;&gt;
        ///                &lt;Length&gt;
        ///                  &lt;P0 type=&quot;path&quot;&gt;
        ///                    //Node5/NomePadre
        ///                  &lt;/P0&gt;
        ///                &lt;/Length&gt;
        ///              &lt;/P0&gt;
        ///
        ///          &lt;/P0&gt;
        ///          &lt;P1 type=&quot;value&quot;&gt;
        ///            &lt;IntBox&gt;
        ///              &lt;Value&gt;5&lt;/Value&gt;
        ///            &lt;/IntBox&gt;
        ///          &lt;/P1&gt;
        ///        &lt;/Greater&gt;
        ///
        ///      &lt;/AND&gt;
        ///    &lt;/PRECONDITIONS&gt;.
        /// </summary>
        public static string EdgePreconditions9 {
            get {
                return ResourceManager.GetString("EdgePreconditions9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TypesValue&gt;&lt;IntBox&gt;
        ///              &lt;Value&gt;18&lt;/Value&gt;
        ///            &lt;/IntBox&gt;&lt;/TypesValue&gt;.
        /// </summary>
        public static string IntboxTest {
            get {
                return ResourceManager.GetString("IntboxTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;XMLSchema1&quot;    
        ///    elementFormDefault=&quot;qualified&quot;   
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///&lt;xs:complexType name=&quot;Node1&quot;&gt;
        ///    &lt;xs:sequence&gt;
        ///
        ///      &lt;xs:element name=&quot;Name&quot; type=&quot;StringBox1&quot;/&gt;
        ///      &lt;xs:element name=&quot;Surname&quot; type=&quot;StringBox1&quot;/&gt;
        ///
        ///    &lt;/xs:sequence&gt;
        ///  &lt;/xs:complexType&gt;
        ///&lt;/xs:schema&gt;.
        /// </summary>
        public static string Node1 {
            get {
                return ResourceManager.GetString("Node1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;Node1&gt;
        ///&lt;Name&gt;
        ///&lt;Value&gt;Pinco&lt;/Value&gt;
        ///&lt;/Name&gt;
        ///&lt;Surname&gt;
        ///&lt;Value&gt;PallinoCognomeLungo&lt;/Value&gt;
        ///&lt;/Surname&gt;
        ///&lt;/Node1&gt;.
        /// </summary>
        public static string Node1Compiled {
            get {
                return ResourceManager.GetString("Node1Compiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;XMLSchema1&quot; 
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///
        ///  &lt;xs:complexType name=&quot;StringBox1&quot;&gt;
        ///    &lt;xs:complexContent&gt;
        ///      &lt;xs:extension base=&quot;StringBox&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///          &lt;xs:element name=&quot;Value&quot; type=&quot;xs:string&quot;/&gt;                 
        ///        &lt;/xs:sequence&gt;
        ///      &lt;/xs:extension&gt;
        ///    &lt;/xs:complexContent&gt;
        ///  &lt;/xs:complexType&gt;
        ///
        ///&lt;/xs:schema&gt;.
        /// </summary>
        public static string Node1Types {
            get {
                return ResourceManager.GetString("Node1Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;XMLSchema1&quot;
        ///    elementFormDefault=&quot;qualified&quot;  
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///&lt;xs:complexType name=&quot;Node2&quot;&gt;
        ///    &lt;xs:sequence&gt;
        ///
        ///      &lt;xs:element name=&quot;Birthday&quot; type=&quot;Date&quot;/&gt;
        ///
        ///    &lt;/xs:sequence&gt;
        ///  &lt;/xs:complexType&gt;
        ///&lt;/xs:schema&gt;.
        /// </summary>
        public static string Node2 {
            get {
                return ResourceManager.GetString("Node2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;Node2&gt;
        ///&lt;Birthday&gt;
        ///&lt;Value&gt;12/12/1912&lt;/Value&gt;
        ///&lt;/Birthday&gt;
        ///&lt;/Node2&gt;.
        /// </summary>
        public static string Node2Compiled {
            get {
                return ResourceManager.GetString("Node2Compiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;XMLSchema1&quot;   
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///
        ///  &lt;xs:complexType name=&quot;Date&quot;&gt;
        ///    &lt;xs:complexContent&gt;
        ///      &lt;xs:extension base=&quot;StringBox&quot;&gt;        
        ///        &lt;xs:sequence&gt;
        ///          &lt;xs:element name=&quot;Value&quot;&gt;
        ///            &lt;xs:simpleType&gt;
        ///              &lt;xs:restriction base=&quot;xs:string&quot;&gt;
        ///                &lt;xs:pattern value=&quot;(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\d\d&quot;/&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Node2Types {
            get {
                return ResourceManager.GetString("Node2Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;XMLSchema1&quot;
        ///    elementFormDefault=&quot;qualified&quot;  
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///&lt;xs:complexType name=&quot;Node3&quot;&gt;
        ///    &lt;xs:sequence&gt;
        ///
        ///      &lt;xs:element name=&quot;DataIscrizione&quot; type=&quot;Date&quot;/&gt;
        ///
        ///    &lt;/xs:sequence&gt;
        ///  &lt;/xs:complexType&gt;
        ///&lt;/xs:schema&gt;.
        /// </summary>
        public static string Node3 {
            get {
                return ResourceManager.GetString("Node3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;Node3&gt;
        ///&lt;DataIscrizione&gt;
        ///&lt;Value&gt;12/12/2009&lt;/Value&gt;
        ///&lt;/DataIscrizione&gt;
        ///&lt;/Node3&gt;.
        /// </summary>
        public static string Node3Compiled {
            get {
                return ResourceManager.GetString("Node3Compiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;XMLSchema1&quot;    
        ///    elementFormDefault=&quot;qualified&quot;   
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///&lt;xs:complexType name=&quot;Node4&quot;&gt;
        ///    &lt;xs:sequence&gt;
        ///
        ///      &lt;xs:element name=&quot;Via&quot; type=&quot;StringBox1&quot;/&gt;
        ///      &lt;xs:element name=&quot;Citta&quot; type=&quot;StringBox1&quot;/&gt;
        ///
        ///    &lt;/xs:sequence&gt;
        ///  &lt;/xs:complexType&gt;
        ///&lt;/xs:schema&gt;.
        /// </summary>
        public static string Node4 {
            get {
                return ResourceManager.GetString("Node4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;Node4&gt;
        ///&lt;Via&gt;
        ///&lt;Value&gt;XXSettembre&lt;/Value&gt;
        ///&lt;/Via&gt;
        ///&lt;Citta&gt;
        ///&lt;Value&gt;Ponsacco&lt;/Value&gt;
        ///&lt;/Citta&gt;
        ///&lt;/Node4&gt;.
        /// </summary>
        public static string Node4Compiled {
            get {
                return ResourceManager.GetString("Node4Compiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;XMLSchema1&quot;    
        ///    elementFormDefault=&quot;qualified&quot;   
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///&lt;xs:complexType name=&quot;Node5&quot;&gt;
        ///    &lt;xs:sequence&gt;
        ///
        ///      &lt;xs:element name=&quot;NomePadre&quot; type=&quot;StringBox1&quot;/&gt;
        ///
        ///    &lt;/xs:sequence&gt;
        ///  &lt;/xs:complexType&gt;
        ///&lt;/xs:schema&gt;.
        /// </summary>
        public static string Node5 {
            get {
                return ResourceManager.GetString("Node5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;Node5&gt;
        ///&lt;NomePadre&gt;
        ///&lt;Value&gt;Asdrubale&lt;/Value&gt;
        ///&lt;/NomePadre&gt;
        ///&lt;/Node5&gt;.
        /// </summary>
        public static string Node5Compiled {
            get {
                return ResourceManager.GetString("Node5Compiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;XMLSchema1&quot;    
        ///    elementFormDefault=&quot;qualified&quot;   
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///&lt;xs:complexType name=&quot;Node6&quot;&gt;
        ///    &lt;xs:sequence&gt;
        ///
        ///      &lt;xs:element name=&quot;NomeFiglio1&quot; type=&quot;StringBox1&quot;/&gt;
        ///      &lt;xs:element name=&quot;NomeFiglio2&quot; type=&quot;StringBox1&quot;/&gt;
        ///    &lt;/xs:sequence&gt;
        ///  &lt;/xs:complexType&gt;
        ///&lt;/xs:schema&gt;.
        /// </summary>
        public static string Node6 {
            get {
                return ResourceManager.GetString("Node6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;Node6&gt;
        ///&lt;NomeFiglio1&gt;
        ///&lt;Value&gt;Marameo&lt;/Value&gt;
        ///&lt;/NomeFiglio1&gt;
        ///&lt;NomeFiglio2&gt;
        ///&lt;Value&gt;TopoGigio&lt;/Value&gt;
        ///&lt;/NomeFiglio2&gt;
        ///&lt;/Node6&gt;.
        /// </summary>
        public static string Node6Compiled {
            get {
                return ResourceManager.GetString("Node6Compiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;workflow_1_node_1&gt;
        ///      &lt;SCHEMA&gt;
        ///        &lt;EXTENDEDTYPES&gt;
        ///          &lt;xs:complexType xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; name=&quot;StringBox0&quot;&gt;
        ///            &lt;xs:complexContent mixed=&quot;false&quot;&gt;
        ///              &lt;xs:extension base=&quot;StringBox&quot;&gt;
        ///                &lt;xs:sequence&gt;
        ///                  &lt;xs:element name=&quot;Value&quot; type=&quot;xs:string&quot;/&gt;
        ///                &lt;/xs:sequence&gt;
        ///              &lt;/xs:extension&gt;
        ///            &lt;/xs:complexContent&gt;
        ///          &lt;/xs:complexType&gt;
        ///          &lt;xs:complexType xmlns:xs=&quot;http://www [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nodeRenderingExample {
            get {
                return ResourceManager.GetString("nodeRenderingExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xs_complexType name=&quot;Nodo1&quot;  &gt;
        ///    &lt;xs_sequence&gt;
        ///      &lt;xs_element name=&quot;Name&quot;/&gt;
        ///      &lt;xs_element name=&quot;Surname&quot;/&gt;
        ///
        ///      &lt;xs_sequence&gt;
        ///        &lt;xs_element name=&quot;NameOnTheCitofon&quot;/&gt;
        ///        &lt;xs_choice&gt;
        ///
        ///          &lt;xs_element name=&quot;ItalianAddress&quot;&gt;
        ///            &lt;xs_complexType&gt;
        ///              &lt;xs_sequence&gt;
        ///                &lt;xs_element name=&quot;Address&quot;/&gt;
        ///
        ///              &lt;/xs_sequence&gt;
        ///            &lt;/xs_complexType&gt;
        ///          &lt;/xs_element&gt;
        ///
        ///          &lt;xs_element name=&quot;AmericanAddress&quot;&gt;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NodeWithComplexTypeRendering {
            get {
                return ResourceManager.GetString("NodeWithComplexTypeRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;a&gt;
        ///  &lt;xs_complexType name=&quot;Nodo1&quot;  &gt;
        ///    &lt;xs_sequence&gt;
        ///      &lt;xs_element name=&quot;Name&quot; /&gt;
        ///      &lt;xs_element name=&quot;Surname&quot; /&gt;
        /// &lt;xs_element name=&quot;scelta&quot;&gt;
        ///&lt;xs_complexType&gt;
        ///&lt;xs_choice&gt;
        ///      &lt;xs_element name=&quot;AddressA&quot; type=&quot;StringBox0&quot;/&gt;
        ///      &lt;xs_element name=&quot;AddressB&quot; type=&quot;StringBox0&quot;/&gt;
        ///&lt;/xs_choice&gt;
        ///&lt;/xs_complexType&gt;
        ///&lt;/xs_element&gt;
        ///      &lt;xs_element name=&quot;AddressInfo&quot; maxOccurs=&quot;10&quot;&gt;
        ///
        ///        &lt;xs_complexType&gt;
        ///          &lt;xs_choice&gt;
        ///            &lt;xs_ele [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NodeWithComplexTypeRendering2 {
            get {
                return ResourceManager.GetString("NodeWithComplexTypeRendering2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///
        ///  &lt;xs:complexType name=&quot;StringBox0&quot;&gt;
        ///    &lt;xs:complexContent&gt;
        ///      &lt;xs:extension base=&quot;StringBox&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///          &lt;xs:element name=&quot;Value&quot; type=&quot;xs:string&quot;/&gt;
        ///        &lt;/xs:sequence&gt;
        ///      &lt;/xs:extension&gt;
        ///    &lt;/xs:complexContent&gt;
        ///  &lt;/xs:complexType&gt;
        ///
        ///
        ///
        ///  &lt;xs:complexType name=&quot;Nodo1&quot;  &gt;
        ///    &lt;xs:sequence&gt;
        ///      &lt;xs:element name=&quot;Name&quot; type=&quot;StringBox0&quot;/&gt;
        ///      &lt;xs:element nam [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NodeWithComplexTypeSchema2 {
            get {
                return ResourceManager.GetString("NodeWithComplexTypeSchema2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///
        ///  &lt;xs:complexType name=&quot;StringBox0&quot;&gt;
        ///    &lt;xs:complexContent&gt;
        ///      &lt;xs:extension base=&quot;StringBox&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///          &lt;xs:element name=&quot;Value&quot; type=&quot;xs:string&quot;/&gt;                 
        ///        &lt;/xs:sequence&gt;
        ///      &lt;/xs:extension&gt;
        ///    &lt;/xs:complexContent&gt;
        ///  &lt;/xs:complexType&gt;
        ///
        ///
        ///
        ///  &lt;xs:complexType name=&quot;Nodo1&quot;  &gt;
        ///    &lt;xs:sequence&gt;
        ///      &lt;xs:element name=&quot;Name&quot; type=&quot;StringBox0&quot;/&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NodeWithComplexTypesSchema {
            get {
                return ResourceManager.GetString("NodeWithComplexTypesSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;Node1&gt;
        ///&lt;Name&gt;
        ///&lt;Valuej&gt;Pinco&lt;/Valuej&gt;
        ///&lt;/Name&gt;
        ///&lt;Surname&gt;
        ///&lt;Value&gt;Pallino&lt;/Value&gt;
        ///&lt;/Surname&gt;
        ///&lt;/Node1&gt;.
        /// </summary>
        public static string NotValidNode1 {
            get {
                return ResourceManager.GetString("NotValidNode1", resourceCulture);
            }
        }
    }
}
