//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.3074
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap _637px_Star_Ouro_svg {
            get {
                object obj = ResourceManager.GetObject("_637px_Star_Ouro_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _637px_Star_Prata_svg {
            get {
                object obj = ResourceManager.GetObject("_637px_Star_Prata_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 10000.
        /// </summary>
        public static string BatterySaveDelay {
            get {
                return ResourceManager.GetString("BatterySaveDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 11112.
        /// </summary>
        public static string CommandPort {
            get {
                return ResourceManager.GetString("CommandPort", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap DefaultBackground {
            get {
                object obj = ResourceManager.GetObject("DefaultBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DefaultBackgroundDark {
            get {
                object obj = ResourceManager.GetObject("DefaultBackgroundDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DeleteButton {
            get {
                object obj = ResourceManager.GetObject("DeleteButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DeleteButtonPressed {
            get {
                object obj = ResourceManager.GetObject("DeleteButtonPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data/.
        /// </summary>
        public static string FormDataSetFolder {
            get {
                return ResourceManager.GetString("FormDataSetFolder", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap FormDownloadedIcon {
            get {
                object obj = ResourceManager.GetObject("FormDownloadedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap FormNotifiedIcon {
            get {
                object obj = ResourceManager.GetObject("FormNotifiedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap FormOpenedIcon {
            get {
                object obj = ResourceManager.GetObject("FormOpenedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HelpButton {
            get {
                object obj = ResourceManager.GetObject("HelpButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HelpHeader {
            get {
                object obj = ResourceManager.GetObject("HelpHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap InformationPanel {
            get {
                object obj = ResourceManager.GetObject("InformationPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LoginH {
            get {
                object obj = ResourceManager.GetObject("LoginH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LoginHeader {
            get {
                object obj = ResourceManager.GetObject("LoginHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MainBackground {
            get {
                object obj = ResourceManager.GetObject("MainBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MainBackgroundWide {
            get {
                object obj = ResourceManager.GetObject("MainBackgroundWide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MobileListener.exe.
        /// </summary>
        public static string MobileListenerExecutable {
            get {
                return ResourceManager.GetString("MobileListenerExecutable", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap NewButton {
            get {
                object obj = ResourceManager.GetObject("NewButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NewButtonPressed {
            get {
                object obj = ResourceManager.GetObject("NewButtonPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NotificationHeader {
            get {
                object obj = ResourceManager.GetObject("NotificationHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 11111.
        /// </summary>
        public static string NotificationPort {
            get {
                return ResourceManager.GetString("NotificationPort", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap PrivateFormButton {
            get {
                object obj = ResourceManager.GetObject("PrivateFormButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PrivateFormButtonPressed {
            get {
                object obj = ResourceManager.GetObject("PrivateFormButtonPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PublicFormButton {
            get {
                object obj = ResourceManager.GetObject("PublicFormButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PublicFormButtonPressed {
            get {
                object obj = ResourceManager.GetObject("PublicFormButtonPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RecentButton {
            get {
                object obj = ResourceManager.GetObject("RecentButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RecentFH {
            get {
                object obj = ResourceManager.GetObject("RecentFH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RecentHeader {
            get {
                object obj = ResourceManager.GetObject("RecentHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ResultsButton {
            get {
                object obj = ResourceManager.GetObject("ResultsButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ResultsButtonPressed {
            get {
                object obj = ResourceManager.GetObject("ResultsButtonPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SettingH {
            get {
                object obj = ResourceManager.GetObject("SettingH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SettingsButton {
            get {
                object obj = ResourceManager.GetObject("SettingsButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SettingsHeader {
            get {
                object obj = ResourceManager.GetObject("SettingsHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SynchButton {
            get {
                object obj = ResourceManager.GetObject("SynchButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 27.237.107.227.
        /// </summary>
        public static string WebServiceAddress {
            get {
                return ResourceManager.GetString("WebServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 49746.
        /// </summary>
        public static string WebServicePort {
            get {
                return ResourceManager.GetString("WebServicePort", resourceCulture);
            }
        }
    }
}
