//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInterface.WorkflowEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ComunicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComunicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebInterface.WorkflowEditor.ComunicationResources", typeof(ComunicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_addArcCall.
        /// </summary>
        internal static string addArcCall {
            get {
                return ResourceManager.GetString("addArcCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_addArcResponse.
        /// </summary>
        internal static string addArcResponse {
            get {
                return ResourceManager.GetString("addArcResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_addFieldCall.
        /// </summary>
        internal static string addFieldCall {
            get {
                return ResourceManager.GetString("addFieldCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_addFieldResponse.
        /// </summary>
        internal static string addFieldResponse {
            get {
                return ResourceManager.GetString("addFieldResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_addNodeCall.
        /// </summary>
        internal static string addNodeCall {
            get {
                return ResourceManager.GetString("addNodeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_addNodeResponse.
        /// </summary>
        internal static string addNodeResponse {
            get {
                return ResourceManager.GetString("addNodeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_createWorkflowCall.
        /// </summary>
        internal static string createWorkflowCall {
            get {
                return ResourceManager.GetString("createWorkflowCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_createWorkflowResponse.
        /// </summary>
        internal static string createWorkflowResponse {
            get {
                return ResourceManager.GetString("createWorkflowResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_finalNodeCall.
        /// </summary>
        internal static string finalNodeCall {
            get {
                return ResourceManager.GetString("finalNodeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_finalNodeResponse.
        /// </summary>
        internal static string finalNodeResponse {
            get {
                return ResourceManager.GetString("finalNodeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_findPredicateCall.
        /// </summary>
        internal static string findPredicateCall {
            get {
                return ResourceManager.GetString("findPredicateCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_findPredicateResponse.
        /// </summary>
        internal static string findPredicateResponse {
            get {
                return ResourceManager.GetString("findPredicateResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_getAuthServiceListCall.
        /// </summary>
        internal static string getAuthServiceListCall {
            get {
                return ResourceManager.GetString("getAuthServiceListCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_getAuthServiceListResponse.
        /// </summary>
        internal static string getAuthServiceListResponse {
            get {
                return ResourceManager.GetString("getAuthServiceListResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFF_getConstraintsCall.
        /// </summary>
        internal static string getConstraintsCall {
            get {
                return ResourceManager.GetString("getConstraintsCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFF_getConstraintsResponse.
        /// </summary>
        internal static string getConstraintsResponse {
            get {
                return ResourceManager.GetString("getConstraintsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_getOperationsCall.
        /// </summary>
        internal static string getOperationsCall {
            get {
                return ResourceManager.GetString("getOperationsCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_getOperationsResponse.
        /// </summary>
        internal static string getOperationsResponse {
            get {
                return ResourceManager.GetString("getOperationsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_getPredicatesCall.
        /// </summary>
        internal static string getPredicatesCall {
            get {
                return ResourceManager.GetString("getPredicatesCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_getPredicatesResponse.
        /// </summary>
        internal static string getPredicatesResponse {
            get {
                return ResourceManager.GetString("getPredicatesResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_initialNodeCall.
        /// </summary>
        internal static string initialNodeCall {
            get {
                return ResourceManager.GetString("initialNodeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_initialNodeResponse.
        /// </summary>
        internal static string initialNodeResponse {
            get {
                return ResourceManager.GetString("initialNodeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_LoadXmlDocFromSessionCall.
        /// </summary>
        internal static string loadXmlDocFromSessionCall {
            get {
                return ResourceManager.GetString("loadXmlDocFromSessionCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_LoadXmlDocFromSessionResponse.
        /// </summary>
        internal static string loadXmlDocFromSessionResponse {
            get {
                return ResourceManager.GetString("loadXmlDocFromSessionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_publishWorkflowCall.
        /// </summary>
        internal static string publishWorkflowCall {
            get {
                return ResourceManager.GetString("publishWorkflowCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_publishWorkflowResponse.
        /// </summary>
        internal static string publishWorkflowResponse {
            get {
                return ResourceManager.GetString("publishWorkflowResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_removeArcCall.
        /// </summary>
        internal static string removeArcCall {
            get {
                return ResourceManager.GetString("removeArcCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_removeArcResponse.
        /// </summary>
        internal static string removeArcResponse {
            get {
                return ResourceManager.GetString("removeArcResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_removeNodeCall.
        /// </summary>
        internal static string removeNodeCall {
            get {
                return ResourceManager.GetString("removeNodeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_removeNodeResponse.
        /// </summary>
        internal static string removeNodeResponse {
            get {
                return ResourceManager.GetString("removeNodeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFE_retrievePredicatesCall.
        /// </summary>
        internal static string retrievePredicatesCall {
            get {
                return ResourceManager.GetString("retrievePredicatesCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFE_retrievePredicatesResponse.
        /// </summary>
        internal static string retrievePredicatesResponse {
            get {
                return ResourceManager.GetString("retrievePredicatesResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFF_saveConstraintsCall.
        /// </summary>
        internal static string saveConstraintsCall {
            get {
                return ResourceManager.GetString("saveConstraintsCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFF_saveConstraintsResponse.
        /// </summary>
        internal static string saveConstraintsResponse {
            get {
                return ResourceManager.GetString("saveConstraintsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_saveWorkflowCall.
        /// </summary>
        internal static string saveWorkflowCall {
            get {
                return ResourceManager.GetString("saveWorkflowCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_saveWorkflowResponse.
        /// </summary>
        internal static string saveWorkflowResponse {
            get {
                return ResourceManager.GetString("saveWorkflowResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_setPropertiesCall.
        /// </summary>
        internal static string setPropertiesCall {
            get {
                return ResourceManager.GetString("setPropertiesCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_setPropertiesResponse.
        /// </summary>
        internal static string setPropertiesResponse {
            get {
                return ResourceManager.GetString("setPropertiesResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_syncNodeCall.
        /// </summary>
        internal static string syncNodeCall {
            get {
                return ResourceManager.GetString("syncNodeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFC_syncNodeResponse.
        /// </summary>
        internal static string syncNodeResponse {
            get {
                return ResourceManager.GetString("syncNodeResponse", resourceCulture);
            }
        }
    }
}
